### ISSUE TITLE
Run once

### ISSUE THREAD

**Issue by DataDrug** [kd8bxp/Arduino-Christmas-Tunes#1]
Hi, I'm trying to setup a small surprise for my brother, but i knwo nothing of arduino. Could you please tell me how to avoid the loop on the selected song?

Thanks!

**Comment by kd8bxp** [comment]
Depends on how/what you are trying to do.....and when you want the song to play.....
So, easy way is to move the code from void loop() to void setup() 
put it under the code in void setup().  void setup() runs once, and is done.
This will let you play the song, and still have code running in void loop(), it will play the song when you plug in the device.

Another way is to put a while(1); at the end of void loop() 
a while statement does something while the condition in the () is true, so a while(1) is always true and never exits. The song will play once, but you'll not be able to have more code run, unless it is in the while(1) (we'll call it a loop) - like
```
while(1) {
do some code....
do some more code....
}
```

So it depends on how you want to do it.... remember to match your {} brackets, and remember void loop() { } still needs to be in the code even if nothing is inside of it.

Those two are probably the easiest to do.

**Comment by DataDrug** [comment]
"move the code from void loop() to void setup()
put it under the code in void setup(). void setup() runs once, and is done.
This will let you play the song, and still have code running in void loop(), it will play the song when you plug in the device."

This was what I was looking for. I'll post the final result here. Thanks!
